use super::types::{Item, Lesson};

pub fn get_content() -> Lesson {
    vec![
        Item {
            traditional: "美",
            simplified: "美",
            phonetic: "Měi",
            english: "Nice, beautiful",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "謝謝",
            simplified: "謝謝",
            phonetic: "Xièxiè",
            english: "Thank you",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "魚",
            simplified: "魚",
            phonetic: "Yú",
            english: "Fish",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "道",
            simplified: "道",
            phonetic: "Dào",
            english: "Road",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "喜",
            simplified: "喜",
            phonetic: "Xǐ",
            english: "Joyful",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "人",
            simplified: "人",
            phonetic: "Rén",
            english: "People",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "家",
            simplified: "家",
            phonetic: "Jiā",
            english: "Family",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "大",
            simplified: "大",
            phonetic: "Dà",
            english: "Big",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "餐",
            simplified: "餐",
            phonetic: "Cān",
            english: "Meal",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "早",
            simplified: "早",
            phonetic: "Zǎo",
            english: "Early",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "上",
            simplified: "上",
            phonetic: "Shàng",
            english: "On",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "久",
            simplified: "久",
            phonetic: "Jiǔ",
            english: "Long",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "見",
            simplified: "見",
            phonetic: "Jiàn",
            english: "See",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "再見",
            simplified: "再見",
            phonetic: "Zàijiàn",
            english: "Goodbye",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "再",
            simplified: "再",
            phonetic: "Zài",
            english: "Again",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "可",
            simplified: "可",
            phonetic: "Kě",
            english: "Can",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "愛",
            simplified: "愛",
            phonetic: "Ài",
            english: "Love",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "為",
            simplified: "為",
            phonetic: "Wèi",
            english: "For",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "認",
            simplified: "認",
            phonetic: "Rèn",
            english: "Recognize, know, admit",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "超",
            simplified: "超",
            phonetic: "Chāo",
            english: "Super",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "國家",
            simplified: "國家",
            phonetic: "Guójiā",
            english: "Country",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "快樂",
            simplified: "快樂",
            phonetic: "Kuàilè",
            english: "Happy",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "可愛",
            simplified: "可愛",
            phonetic: "Kě'ài",
            english: "Cute",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "大哥",
            simplified: "大哥",
            phonetic: "Dàgē",
            english: "Big brother",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
        Item {
            traditional: "天",
            simplified: "天",
            phonetic: "Tiān",
            english: "Day",
            english_alternate_choices: vec!["hi", "blah", "moon"],
        },
    ]
}
