use super::types::{Item, Lesson};

pub fn get_content() -> Lesson {
    vec![
        Item {
            simplified: "一",
            traditional: "一",
            pinyin: "yī",
            english: "one",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "二",
            traditional: "二",
            pinyin: "èr",
            english: "two",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "三",
            traditional: "三",
            pinyin: "sān",
            english: "three",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "四",
            traditional: "四",
            pinyin: "sì",
            english: "four",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "五",
            traditional: "五",
            pinyin: "wǔ",
            english: "five",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "六",
            traditional: "六",
            pinyin: "liù",
            english: "six",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "七",
            traditional: "七",
            pinyin: "qī",
            english: "seven",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "八",
            traditional: "八",
            pinyin: "bā",
            english: "eight",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "九",
            traditional: "九",
            pinyin: "jiǔ",
            english: "nine",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "十",
            traditional: "十",
            pinyin: "shí",
            english: "ten",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "零",
            traditional: "零",
            pinyin: "líng",
            english: "zero",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "两",
            traditional: "两",
            pinyin: "liǎng",
            english: "two",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "百",
            traditional: "百",
            pinyin: "bǎi",
            english: "hundred",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "千",
            traditional: "千",
            pinyin: "qiān",
            english: "thousand",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "第一",
            traditional: "第一",
            pinyin: "dìyī",
            english: "first",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "个",
            traditional: "个",
            pinyin: "gè",
            english: "one,",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "岁",
            traditional: "岁",
            pinyin: "suì",
            english: "year",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "本",
            traditional: "本",
            pinyin: "běn",
            english: "volume",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "些",
            traditional: "些",
            pinyin: "xiē",
            english: "some",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "块",
            traditional: "块",
            pinyin: "kuài",
            english: "piece",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "次",
            traditional: "次",
            pinyin: "cì",
            english: "number",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "公斤",
            traditional: "公斤",
            pinyin: "gōngjīn",
            english: "kilogram",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "元",
            traditional: "元",
            pinyin: "yuán",
            english: "yuan",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "件",
            traditional: "件",
            pinyin: "jiàn",
            english: "piece",
            english_alternate_choices: vec![""],
        },
        Item {
            simplified: "张",
            traditional: "张",
            pinyin: "zhāng",
            english: "sheet",
            english_alternate_choices: vec![""],
        },
    ]
}
