version: 2
jobs:
  tests:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check Formatting
          command: |
            rustup component add rustfmt
            cargo fmt -- --check
      - run:
          name: Unit Tests
          command: |
            cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  version: 2
  tests:
    jobs:
      - tests:
          filters:
            branches:
              ignore: master