version: 2

jobs:
  filters:
    branches:
      ignore: master
  tests:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check Formatting
          command: |
            rustup component add rustfmt
            cargo fmt -- --check
      - run:
          name: Unit Tests
          command: |
            cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
